{"trial_id": "0000", "hyperparameters": {"space": [{"class_name": "Boolean", "config": {"name": "timeseries_block_1/rnn_block_1/bidirectional", "default": true, "conditions": []}}, {"class_name": "Choice", "config": {"name": "timeseries_block_1/rnn_block_1/layer_type", "default": "lstm", "conditions": [], "values": ["gru", "lstm"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "timeseries_block_1/rnn_block_1/num_layers", "default": 2, "conditions": [], "values": [1, 2, 3], "ordered": true}}, {"class_name": "Choice", "config": {"name": "regression_head_1/dropout", "default": 0, "conditions": [], "values": [0.0, 0.25, 0.5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "sgd", "adam_weight_decay"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "values": [0.1, 0.01, 0.001, 0.0001, 2e-05, 1e-05], "ordered": true}}], "values": {"timeseries_block_1/rnn_block_1/bidirectional": true, "timeseries_block_1/rnn_block_1/layer_type": "lstm", "timeseries_block_1/rnn_block_1/num_layers": 3, "regression_head_1/dropout": 0.5, "optimizer": "adam_weight_decay", "learning_rate": 0.01}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/autokeras/engine/tuner.py\", line 91, in _build_and_fit_model\n    model = self._try_build(trial.hyperparameters)\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 155, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 146, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/hypermodel.py\", line 115, in _build_wrapper\n    return self._build(hp, *args, **kwargs)\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/autokeras/graph.py\", line 262, in build\n    return self._compile_keras_model(hp, model)\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/autokeras/graph.py\", line 324, in _compile_keras_model\n    model.compile(\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/zach/miniconda3/envs/tf/lib/python3.9/site-packages/keras/saving/legacy/serialization.py\", line 368, in class_and_config_for_serialized_keras_object\n    raise ValueError(\nValueError: Unknown optimizer: 'adamweightdecay'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.\n"}